# This is a basic workflow to help you get started with Actions

name: Environment variable tests

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name: 
        description: 'The name'
        required: true
        default: 'Jeremy'
      age:
        description: 'The age'
        required: true
        default: '42'
    
  repository_dispatch:
    types: env
    
env:
  NAME: ${{ github.event.inputs.name || github.event.client_payload.name }}
  AGE: ${{ github.event.inputs.age }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check environment variables set
        run: |
          echo ${{ env.NAME }}
          echo ${{ env.AGE }}

